require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("./database");
const Product = require("./models/Product");

const sampleProducts = [
  {
    name: "CeraVe 100% Mineral Sunscreen SPF 30",
    brand: "CeraVe",
    image: "/images/cerave.jpg",
    price: 4,
    oldPrice: 500,
    discount: 50,
    rating: 4.3,
    reviews: 2464,
    size: "5 Fl Oz",
    category: "sun care",
  },
  {
    name: "CeraVe 100% Mineral Sunscreen SPF 30",
    brand: "CeraVe",
    image: "/images/cerave.jpg",
    price: 450,
    oldPrice: 500,
    discount: 50,
    rating: 4.3,
    reviews: 2464,
    size: "5 Fl Oz",
    category: "sun care",
  },
  {
    name: "Cetaphil Sun SPF 50+ Light Gel - 50 ml",
    brand: "Cetaphil",
    image: "/images/cetaphil.png",
    price: 969.24,
    oldPrice: 1182,
    discount: 18,
    rating: 4.3,
    reviews: 646,
    size: "50 ml",
    category: "sun care",
  },
  {
    name: "COSMEDIX Hydrate Plus Sunscreen with Broad Spectrum SPF 17",
    brand: "COSMEDIX",
    image: "/images/cosmedix.jpg",
    price: 4565,
    oldPrice: 4845,
    discount: 280,
    rating: 4.3,
    reviews: 112,
    size: "2 Ounce (Pack of 1)",
    category: "sun care",
  },
  {
    name: "Episoft AC Moisturizer with Sunscreen - 75g",
    brand: "Glenmark",
    image: "/images/episoft.jpg",
    price: 492.03,
    oldPrice: 639,
    discount: 23,
    rating: 4.2,
    reviews: 630,
    size: "75g",
    category: "sun care",
  },
  {
    name: "La Shield Broad Spectrum SPF 40+ PA+++ Anti Acne Sunscreen - 60g",
    brand: "La Shield",
    image: "/images/laShield.jpg",
    price: 646,
    oldPrice: 850,
    discount: 24,
    rating: 4.4,
    reviews: 700,
    size: "60g",
    category: "sun care",
  },
  {
    name: "The Derma Co 1% Hyaluronic Sunscreen Aqua Gel With SPF 50",
    brand: "The Derma Co",
    image: "/images/dermaco.jpg",
    price: 506.22,
    oldPrice: 649,
    discount: 22,
    rating: 4.3,
    reviews: 81,
    size: "80g",
    category: "sun care",
  },

  // Skincare Products
  {
    name: "NEOSTRATA Skin Active Triple Firming Neck Cream",
    brand: "NEOSTRATA",
    image: "/images/neostrata.jpg",
    price: 8120,
    oldPrice: 9400,
    discount: 1280,
    rating: 4.2,
    reviews: 903,
    size: "2.8 Ounce",
    category: "skincare",
  },
  {
    name: "e.l.f. SKIN Holy Hydration! Hydrated Ever After Skincare Mini Kit",
    brand: "e.l.f. SKIN",
    image: "/images/elf.jpg",
    price: 1660,
    oldPrice: 1800,
    discount: 140,
    rating: 4.5,
    reviews: 6214,
    size: "1 Count",
    category: "skincare",
  },
  {
    name: "ANUA Heartleaf Quercetinol Pore Deep Cleansing Foam",
    brand: "ANUA",
    image: "/images/anua.jpg",
    price: 1080,
    oldPrice: 1300,
    discount: 220,
    rating: 4.6,
    reviews: 7808,
    size: "5.07 Fl Oz",
    category: "skincare",
  },
  {
    name: "Under Eye Patches - 60 Pcs - 24K Gold Eye Mask",
    brand: "Gold Eye",
    image: "/images/eyepatch.jpg",
    price: 660,
    oldPrice: 900,
    discount: 240,
    rating: 4.3,
    reviews: 11958,
    size: "60 Count",
    category: "skincare",
  },
  {
    name: "medicube Collagen Jelly Cream - Niacinamide & Freeze-Dried Hydrolyzed Collagen",
    brand: "medicube",
    image: "/images/medicube.jpg",
    price: 1640,
    oldPrice: 1900,
    discount: 260,
    rating: 4.4,
    reviews: 3367,
    size: "3.71 Fl Oz",
    category: "skincare",
  },
  {
    name: "Aquaphor Healing Balm Stick",
    brand: "Aquaphor",
    image: "/images/aquaphor.jpg",
    price: 830, // INR
    oldPrice: 875,
    discount: 45,
    rating: 4.7,
    reviews: 9690,
    size: "0.65 Ounce",
    category: "body care", 
  },
  {
    name: "Dove Brown Sugar and Coconut Body Scrub",
    brand: "Dove",
    image: "/images/dove.jpg",
    price: 665, 
    oldPrice: 915,
    discount: 250,
    rating: 4.6,
    reviews: 178,
    size: "15 Ounce",
    category: "body care",
  },
  {
    name: "Bio-Oil Skincare Body Oil Serum",
    brand: "Bio-Oil",
    image: "/images/bio.jpg",
    price: 930, 
    oldPrice: 1140,
    discount: 210,
    rating: 4.7,
    reviews: 53300,
    size: "2 Fl Oz",
    category: "body care",
  },
  {
    name: "Hemp Body Lotion with Pump",
    brand: "Personal Care",
    image: "/images/hemp.jpg",
    price: 460, 
    oldPrice: 625,
    discount: 165,
    rating: 4.3,
    reviews: 314,
    size: "13.5 Fl Oz",
    category: "body care",
  },
  {
    name: "Tree Hut Vanilla Foaming Gel Wash",
    brand: "Tree Hut",
    image: "/images/tree.jpg",
    price: 750, 
    oldPrice: 920,
    discount: 170,
    rating: 4.5,
    reviews: 9025,
    size: "18 Fl Oz",
    category: "body care",
  },
  {
    name: "OGX Sensitive + Pink Sea Salt & Rosewater Body Scrub",
    brand: "OGX",
    image: "/images/ogx.jpg",
    price: 580, 
    oldPrice: 730,
    discount: 150,
    rating: 4.5,
    reviews: 29390,
    size: "19.5 Fl Oz",
    category: "body care",
  },
  {
    name: "L'Oreal Paris Extraordinary Oil Hair Serum",
    brand: "L'Oreal Paris",
    image: "/images/loreal.jpg",
    price: 499,
    oldPrice: 650,
    discount: 23,
    rating: 4.5,
    reviews: 1300,
    size: "100 ml",
    category: "hair care",
  },
  {
    name: "WOW Skin Science Onion Black Seed Hair Oil",
    brand: "WOW",
    image: "/images/wow.jpg",
    price: 299,
    oldPrice: 399,
    discount: 25,
    rating: 4.3,
    reviews: 2500,
    size: "150 ml",
    category: "hair care",
  },
  {
    name: "Mamaearth Onion Hair Oil with Redensyl",
    brand: "Mamaearth",
    image: "/images/mamaearth.jpg",
    price: 449,
    oldPrice: 599,
    discount: 25,
    rating: 4.4,
    reviews: 3400,
    size: "250 ml",
    category: "hair care",
  },
  {
    name: "Biotique Bio Bhringraj Therapeutic Hair Oil",
    brand: "Biotique",
    image: "/images/biotique.jpg",
    price: 180,
    oldPrice: 250,
    discount: 28,
    rating: 4.2,
    reviews: 1500,
    size: "120 ml",
    category: "hair care",
  },
  {
    name: "Indulekha Bringha Hair Oil",
    brand: "Indulekha",
    image: "/images/indulekha.jpg",
    price: 385,
    oldPrice: 435,
    discount: 12,
    rating: 4.3,
    reviews: 5200,
    size: "100 ml",
    category: "hair care",
  },
  {
    name: "Tresemme Keratin Smooth Shampoo",
    brand: "Tresemme",
    image: "/images/tresemme.jpg",
    price: 520,
    oldPrice: 650,
    discount: 20,
    rating: 4.5,
    reviews: 7600,
    size: "580 ml",
    category: "hair care",
  },
  {
    name: "Herbal Essences Argan Oil of Morocco Shampoo",
    brand: "Herbal Essences",
    image: "/images/herbal.jpg",
    price: 625,
    oldPrice: 799,
    discount: 22,
    rating: 4.6,
    reviews: 3200,
    size: "400 ml",
    category: "hair care",
  },
  {
    name: "Dove Intense Repair Shampoo",
    brand: "Dove",
    image: "/images/dove1.jpg",
    price: 310,
    oldPrice: 400,
    discount: 22,
    rating: 4.4,
    reviews: 8900,
    size: "650 ml",
    category: "hair care",
  },
  {
    name: "L'Oreal Paris 6 Oil Nourish Conditioner",
    brand: "L'Oreal Paris",
    image: "/images/loreal1.jpg",
    price: 225,
    oldPrice: 299,
    discount: 25,
    rating: 4.5,
    reviews: 2600,
    size: "175 ml",
    category: "hair care",
  }
];

const seedProducts = async () => {
  try {
    console.log(" Connecting to database...");
    await connectDB();

    console.log(" Deleting all old products...");
    await Product.deleteMany({});

    console.log(" Inserting new products...");
    await Product.insertMany(sampleProducts);
    console.log(` Inserted ${sampleProducts.length} products.`);

    console.log(" Categories now in DB:", await Product.distinct("category"));
  } catch (error) {
    console.error(" Error inserting products:", error);
  } finally {
    console.log(" Closing database connection...");
    await mongoose.disconnect();
    process.exit();
  }
};

seedProducts();